server.port=8090

# Conexion a H2 en memoria. "productosdb" es el nombre de la base, podes cambiarlo.
# Cambiamos conexión de H2 en memoria a un archivo.
spring.datasource.url=jdbc:h2:file:./data/productosdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=

# Ejecuta schema.sql (y data.sql si existe) al levantar la app
spring.sql.init.mode=always

# Habilita la consola web de H2 en /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
