spring.application.name=weather-openweather-mvc
server.port=8080

spring.thymeleaf.cache=false

# OpenWeather
# No guardar la API key real en Git.
openweather.api-key=${OPENWEATHER_API_KEY:}
openweather.base-url=https://api.openweathermap.org/data/2.5/weather
